const sampleData = {
  users: [
    {
      name: 'Admin',
      email: 'nhkhang061203@gmail.com',
      password: '123456',
      role: 'admin',
    },
    {
      name: 'User',
      email: 'khanggg061203@gmail.com',
      password: '123456',
      role: 'user',
    },
  ],
  products: [
    {
      name: 'Dưa lưới tròn ruột cam',
      slug: 'dua-luoi-cam-ruot-cam',
      category: 'Trái cây',
      description: 'Dưa lưới tròn ruột cam trái từ 1 - 2kg',
      images: [
        '/images/sample-products/p1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: 2.99,
      brand: 'MP-Gaden',
      rating: 4.5,
      numReviews: 10,
      stock: 25,
      isFeatured: true,
      banner: '/images/banner-1.jpg',
    },
    {
      name: 'Thanh long',
      slug: 'thanh-long',
      category: 'Trái cây',
      description: 'Thanh long 1kg (trái từ 350g)',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: 1.95,
      brand: 'Long An',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: '/images/banner-2.jpg',
    },
    {
      name: 'Quýt Úc',
      slug: 'quyt-uc',
      category: 'Trái cây',
      description: 'Quýt giống Úc 1 kg (8 - 10 trái)',
      images: [
        '/images/sample-products/p3-1.jpg',
        '/images/sample-products/p3-2.jpg',
      ],
      price: 3.55,
      brand: 'Úc',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Ba rọi heo',
      slug: 'ba-roi-heo',
      category: 'Thịt',
      description: 'Ba rọi heo nhập khẩu Nga túi 500g',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 4.99,
      brand: 'Nga',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Sữa TH true MILK',
      slug: 'sua-th-true-milk',
      category: 'Đồ uống',
      description:
        'Thùng 48 hộp sữa tươi tiệt trùng nguyên chất TH true MILK 180ml',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: 16.55,
      brand: 'TH True Milk',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Bia Sài Gòn Special Sleek',
      slug: 'bia-sai-gon-special-sleek',
      category: 'Đồ uống',
      description: 'Thùng 24 lon bia Sài Gòn Special Sleek 330ml',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 13.88,
      brand: 'Polo',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
